version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["yarn", "serve"]
